### ISSUE TITLE
Documents with URL IDs should be queryable

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1638]
```clojure
(defn start-xtdb!
  []
  (letfn [(kv-store [dir]
                    {:kv-store {:xtdb/module 'xtdb.rocksdb/->kv-store,
                                :db-dir      (io/file dir),
                                :sync?       true}})]
    (xt/start-node
     {:xtdb/tx-log         (kv-store "data/dev/tx-log"),
      :xtdb/document-store (kv-store "data/dev/document-store"),
      :xtdb/index-store    (kv-store "data/dev/index-store")})))

(->> (xt/submit-tx @node [[::xt/put {:xt/id (URL. "http://localhost:3000") :a/b 1}]])
     (xt/await-tx @node))
;; => #:xtdb.api{:tx-time #inst "2021-10-09T10:17:02.304-00:00", :tx-id 0}

(->> (xt/submit-tx @node [[::xt/put {:xt/id "xyz" :a/b 1}]])
     (xt/await-tx @node))
;; => #:xtdb.api{:tx-time #inst "2021-10-09T10:17:04.240-00:00", :tx-id 1}

(xt/entity (xt/db @node) (URL. "http://localhost:3000"))
;; => {:a/b 1, :xt/id #object[java.net.URL 0x10157555 "http://localhost:3000"]}

(xt/entity (xt/db @node) "xyz")
;; => {:a/b 1, :xt/id "xyz"}

(xt/q (xt/db @node) '{:find [?e] :where [[?e :a/b 1]]})
;; => #{["xyz"]} ;; expecting the URL here also
```

URI IDs can be used as a workaround.

Current URL test coverage looks very limited:
https://github.com/xtdb/xtdb/blob/e2f51ed99fc2716faa8ad254c0b18166c937b134/test/test/xtdb/tx_test.clj#L864-L866
https://github.com/xtdb/xtdb/blob/e2f51ed99fc2716faa8ad254c0b18166c937b134/core/test/xtdb/codec_test.clj#L159-L160

**Comment by deobald** [comment]
Original bug report: https://clojurians.zulipchat.com/#narrow/stream/185617-xtdb/topic/Slack.20archive/near/256858161

**Comment by jarohen** [comment]
Ok, this was a fun one to track down.

`value->buffer` for URLs falls back to the Object implementation, which hashes the serialized representation of the object. In the case of URLs, this includes the hashCode of the object, or `-1` if the hashCode hasn't been calculated yet. Even if the hashCode has been calculated, it may not be the same hashCode for what we'd consider the same URL, because the URL resolves the DNS name to an IP address - if the domain name has multiple IP addresses, you might get one of many hash-codes. Not ideal!

Worth analysing impact of this hashing behaviour - it may be wider than just document IDs, but thankfully `id->buffer` isn't vulnerable to this issue thanks to its use of `.toExternalForm`. Safe to say, for any proposed change to how we hash URLs, we'll have to consider the impact on backwards compatibility of URLs already in XT instances. Needs further thought!

**Comment by jarohen** [comment]
Advice for now would be to use URIs where possible - update docs to remove from valid types.

**Comment by tekacs** [comment]
I started to update the docs to remove the reference to URL as a valid type (because I was worried I'd forget about this issue and use URLs at some point 😆 ), but I ran into a quirk:

This is what the docs say:
- https://docs.xtdb.com/language-reference/1.20.0/datalog-transactions/#valid-ids
- https://github.com/xtdb/xtdb/blob/master/docs/language-reference/modules/ROOT/pages/datalog-transactions.adoc#valid-ids

```asciidoc
|URI|`#xtdb/id "mailto:hello@xtdb.com"`
|URI|`#xtdb/id "https://github.com/xtdb/xtdb"`
```
> The `#xtdb/id` reader literal will take URI/URL strings and attempt to coerce them into valid IDs.
> 
> URIs and URLs are interpreted using Java classes (java.net.URI and java.net.URL respectively) and therefore you can also use these directly.

But the actual reader tag implementation seems to _only_ use `java.net.URL`, not using URI at all:

https://github.com/xtdb/xtdb/blob/afd581b4747f18b1332a470ff94174abc6a25947/core/src/xtdb/codec.clj#L723-L734
https://github.com/xtdb/xtdb/blob/afd581b4747f18b1332a470ff94174abc6a25947/core/src/xtdb/codec.clj#L525-L528

It looks like that's what's actually allowing these examples to currently run -- they do convert back into strings after they're done, but this belies the documentation's comment that `java.net.URL` and `java.net.URI` are used respectively (at least by the reader) -- they may be parsed correctly using the right tools later in the process?

![CleanShot 2021-12-19 at 11 27 59](https://user-images.githubusercontent.com/63247/146682683-c98a4c3e-fb89-439e-b7cb-b463f5e03591.png)

**Comment by jarohen** [comment]
Thanks @tekacs, good spot! I've removed the references to `#xtdb/id` from the docs too. We unfortunately have to keep the reader behaving this way as there could be serialized data depending on this representation, but we no longer recommend it as a user-facing API.

I've also removed URLs from that list and added a note - we'd recommend against their use going forward.

Cheers,

James
