### ISSUE TITLE
Clock difference between computer running xtdb node and computer running postgresql db configured as document store and tx log leads to read-your-writes inconsistency

### ISSUE THREAD

**Issue by ema-fox** [xtdb/crux#1665]
Steps to reproduce:
use xtdb on a computer whose clock is 5 seconds behind the postgresql server configured as document store and tx log
```
(let [id (UUID/randomUUID)
      tx (xt/submit-tx node [[:xt/put {:xt/id id :foo 5}]])]
  (xt/await-tx node tx)
  (xt/entity (xt/db node {::xt/tx tx}) id))
```
Actual result:
nil
Expected result:
The doc that was just put into the db.

**Comment by jarohen** [comment]
Hey @ema-fox, thanks for getting in touch - this sounds like it was a fun one to track down! :sweat_smile: 

My initial suspicion for this is that it's the valid-time of the `db` that's causing the issue here - if it's not provided, it defaults to `now` on the XT node, which (in this case) is 'before' the transaction was submitted. Could you check your example with `(xt/db node {::xt/tx tx, ::xt/valid-time (::xt/tx-time tx)})` to confirm?

Cheers,

James

**Comment by ema-fox** [comment]
Yes indeed, passing the valid-time in the manner you suggested does lead to the just written version of the doc being returned.

**Comment by ema-fox** [comment]
Some thoughts on whether just enabling NTP on the computers involved is enough.
The issue doesn't show up with NTP enabled, however since NTP can't completely eliminate clock differences only minimize them this seems to rely on network + processing delay being bigger than the clock difference to ensure that `now` on the node is >= the valid time. So enabling NTP only solves the issue in practice but not in theory.

**Comment by jarohen** [comment]
Agreed - shouldn't ever _rely_ on NTP to fix this class of issues!

**Comment by pekeler** [comment]
Is this a dupe or why was the issue closed?

**Comment by refset** [comment]
Hi @pekeler in short, there doesn't seem to be anything obvious/easy that XT can change internally to prevent such situations (e.g. without adding a timestamp oracle to the architecture), but I am planning to add a new subsection to the docs with guidance on this and the overall topic of "Consistency", as it's definitely a subtle thing to troubleshoot and get _correct_.

In the meantime, here is an untested suggestion that _may_ be helpful for solving this specific scenario (in both practice and theory!):

```clojure
(defn read-your-write-valid-time [{:keys [::xt/tx-time] :as tx-receipt}]
  (let [node-local-time (Date.)]
    {::xt/tx tx-receipt
     ::xt/valid-time (if (< (inst-ms node-local-time) (inst-ms tx-time))
                       (do (log/warn "Local node clock is lagging too far behind the tx-log clock - compensating action taken")
                           tx-time)
                       node-local-time)}))
    
(xt/db node (read-your-write-valid-time tx-receipt))
```
...this could possibly be a safer default behaviour, but I'm probably missing something :thinking:

**Comment by whmountains** [comment]
I just ran across this issue with NTP *enabled*.  The default timeserver provided with MacOS is quite far away geographically, and that created an offset sufficient to cause me to not be able to read my writes.  Thank you so much @refset for helping me identify what was going on.

I'm not sure how much can be done without significantly complicating XTDB, but it's something to be aware of.

**Comment by jarohen** [comment]
Thanks @whmountains and @refset :pray: 

We've been discussing an XT solution whereby we default document valid-times to the clock on the submitting node, rather than on the tx-log (valid time currently defaults to tx-time if not provided, which comes from the tx-log). This means that, when we compare the valid-time on the `db` instance to the valid-time on the document, they should have both come from the same (possibly skewed) clock. (If that clock's not always increasing, that's a different issue!).

Assuming the two clocks are _roughly_ in sync, the change in behaviour shouldn't be too noticeable to end users.

In any event, while this might be a relatively straightforward change (it probably wouldn't be too onerous), we don't tend to rush changes of this nature - they often have non-obvious impacts! One to ponder :thinking: 

James
