### ISSUE TITLE
`pull-many` should return results in the same order as the input eids

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#1714]
(from @refset) 

matches datascript behaviour https://clojurians.slack.com/archives/CG3AM2F7V/p1644395837107869

**Comment by eneroth** [comment]
Thanks so much for this @jarohen! This makes it much easier to return predictable results to Pathom. The ability to distinguish between entities that do not exist in the DB, vs. those that do, but did not match the query, is a welcome added bonus that turned out to be useful for us.

Ping @wilkerlucio
