### ISSUE TITLE
Handling of stats for evicted entities.

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#1804]
Consider the following code snippet:
```clj
  (def mem-node1 (xt/start-node {}))

  (xt/submit-tx mem-node1 [[::xt/put {:xt/id 1 :data/foo 1}]])
  (xt/submit-tx mem-node1 [[::xt/evict 1]])

  (xt/attribute-stats mem-node1)
  ;; => {:data/foo 1, :xt/id 1}
```
Copying @refset 's  thoughts on this from a thread. There are two aspects to this:
- the accuracy of the stats - implicitly these shouldn't need to be accurate, as they are intended only to aid query planning and are not to provide a fully consistent view. From this point of view it is purely a "nice to have" for the eviction to decrement the stats
- the attribute itself may be needed to be regarded as sensitive also and therefore eviction should apply - how/whether to implement this though, in the face of a non-fully consistent/accurate view

Personally I think that even the first case is worth having. On the one hand it's nice to have accurate stats on the attributes of the current db (for example useful when doing a tx-log rewrite). On the other hand having lots of evicted attribute counts in the stats might lead the query planner down a wrong path.

**Comment by jarohen** [comment]
The attribute-stats are only approximations, and shouldn't be relied upon to be 100% accurate - as you say, they're only required to guide the query planner. Ensuring these are completely accurate would involve a tradeoff in ingestion speed that wouldn't benefit the query planner (which is really only interested in _relative_ cardinalities). Over time the attribute stats have come to use more statistical estimations (e.g. hyper-log-log) under the hood, rather than accurate counts - again to optimise ingestion/storage - so this divergence will likely increase.

It is assumed that attributes themselves do not contain any personally-identifiable information (PII), and hence shouldn't be necessary to evict.

**Comment by refset** [comment]
> Ensuring these are completely accurate would involve a tradeoff in ingestion speed 

Definitely. Also note that whilst stats are now (once again) being processed on a separate "stats-executor" thread (currently unreleased on `master`), adding any additional concurrent query workload during ingestion would still negatively impact overall ingestion performance.
