### ISSUE TITLE
Hardening the checkpoint restore process

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#1868]
Verifying the integrity of the downloaded checkpoint, ensuring that we don't try to restore an incomplete/corrupted checkpoint, nor start a node having done so.

* Anything we can do at the OS-level to make this more resilient?

**Comment by jsulmont** [comment]
Regardless the Checkpoint Store, an XTDB checkpoint consists in 2 parts: a directory (containing the actual checkpoint data) and an EDN file, that summarises that checkpoint (e.g. `tx`, directory name, checkpoint-time). When it detects that a restore is needed (i.e., `index-store` is missing), XTDB asks the checkpoint storage for a list of checkpoints (i.e., a list of these EDN files) and restores from the most recent found (if any).

Given that:
* XT writes first the directory, then only if successful writes the EDN
* a restore can only happen if at least one EDN file has been *successfully* written.

and leaving aside (for now) the corruption case, we have to address the following situations:
1. the upload of the actual checkpoint directory (first part) fails,
2. the upload of the EDN file (second part) fails.

* In the first case, we're left with an incomplete checkpoint on the storage; since no EDN has been written, there is no risk for those files to be used in a restore.
* In the second case, the restore is complete, but unusable since no EDN written: we're left with an complete but unusable checkpoint.

That is, in both cases whatever has been written in the fails attempt, is unusable: **the corrective action is to cleanup whatever was written by the checkpoint attempt.** 

About corruption: a checkpoint can be corrupted when an individual file has been corrupted, either at transfer time (OS facility) or afterwards (e.g. deliberately by adding/removing/tempering).

Currently XTDB copies individual files using the OS facilities offered by the chosen checkpoint store: Java NIO, S3 or GCP.
We can safely assume these will throw some exception upon failure, resulting in other 1. or 2. above. 
We're not a blockchain and there isn't much we can do to prevent Operational fault (or malicious attacks).

**Comment by jarohen** [comment]
covered by @jsulmont's recent work
