### ISSUE TITLE
Easy way for jack-in to re-prep sub-modules if required

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2115]
Ideally, `cider-jack-in` (or equivalent in other editors) would re-compile the Java classes in all the sub-modules before starting a REPL.

**Comment by hraberg** [comment]
It also applies when running the tests from command line, but this is likely more easily solved. The root cause is when you pull and someone else has changed a `.java` file without you knowing this. What I really want is a flag `:auto-prep` in deps, that is, prep anything that needs to be prepped in any source dependency (including self, of course) before launching a JVM for any reason.

**Comment by jarohen** [comment]
fixed with Gradle
