### ISSUE TITLE
Roundtripping of ISO8601 timestamps (including 'T' and 'Z')

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2279]
ISO8601 timestamps are currently returned like so by typical pgwire queries:
```
       system_time_start       
-------------------------------
 "2022-09-11T15:13:53.846919Z"
 "2022-09-11T15:14:00.376721Z"
 "2022-09-11T15:14:06.605243Z"
 "2022-09-11T15:14:11.991653Z"
 "2022-09-11T15:14:17.017727Z"
 "2022-09-11T15:14:42.592297Z"
(6 rows)
 ```

However these can't currently be parsed when used verbatim in queries:
```
SELECT Prop_Owner.customer_number
  FROM Prop_Owner
         FOR SYSTEM_TIME AS OF TIMESTAMP '2022-09-11T15:13:53.846919Z';
```

```
ERROR:  Parse error at line 3, column 53:
LINE 3: ...       FOR SYSTEM_TIME AS OF TIMESTAMP '2022-09-11T15:13:53....
                                                             ^
DETAIL:           FOR SYSTEM_TIME AS OF TIMESTAMP '2022-09-11T15:13:53.846919Z'
                                                    ^
Expected:
<WS>
```

The workaround is to manually replace the 'T' with ' ' and remove the 'Z' from the literal, and add `+00:00`:
```
SELECT Prop_Owner.customer_number
  FROM Prop_Owner
         FOR SYSTEM_TIME AS OF TIMESTAMP '2022-09-11 15:13:53.846919+00:00';
```

If you don't add the `+00:00` though, then it "parses fine" (doesn't error) but it won't actually work (I've not investigate beyond that) - possibly a separate issue altogether(?)

Perhaps the real issue here lies with the pgwire response formatting in the first place, though I would expect these literals to still be parse-able.

Discussion https://juxt.slack.com/archives/G018EA25K71/p1662922971249579

**Comment by jarohen** [comment]
@refset Postgres has [DateStyle](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-DATESTYLE)/[IntervalStyle](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-INTERVALSTYLE) for this. If memory serves it defaults to the SQL standard, but can also output ISO on a per-session basis.

Maybe the best thing we can do for now is to explicitly handle timestamps in the pgwire driver (rather than returning them as JSON) and then see what psql does for us out of the box
