### ISSUE TITLE
Interval comparison / equality (§8.2)

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2307]
p439, §8.2 general rule 7.

* Can only compare within year-month and within month-day-nanos.
* Roughly: convert to the lowest common interval unit, convert to integer and compare.
* Additional fun for us is within MDN intervals (for non-zero months, which don't exist in SQL) - we have a few options:
  1. prevent it, statically - type error
  2. dynamically allow it, runtime error for non-zero months
  3. same, but say that intervals with same months are comparable, different months compare to null
  4. magically convert 30d=1m (like Postgres)

  If we go for 3 or 4, we could extend the comparisons to between YM/DT/MDN, but we lose the invariant that 'X + A = R and X + B = R iff A = B'.

**Comment by danmason** [comment]
Going to make an initial cut of this, in particular:
- Comparing only within same typed intervals.
- For year-month intervals:
  - Convert to total months, compare that.
- For month-day-nano intervals:
  - Will throw a runtime error if either has `months > 0` (we have a few other places where in general we handle MDNs that way, so shall stick with it)
  - Otherwise, convert to a total count of the MDN in `nanos` and compare that.
