### ISSUE TITLE
Arrow memory leak error if transaction function has an unhandled exception

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2489]
Add a `(throw (RuntimeException.))` in various places in `->call-indexer`'s `indexOp` and run `xtdb.tx-fn-test` - something's not getting cleaned up correctly

**Comment by mbutlerw** [comment]
Issue arises when a partially processed transaction is aborted, this is because the temporal indexer has allocated vectors for the data that has already been processed, however the abort method makes no attempt to clean up these resources. 

See test below for a repro:

```
(deftest test-indexer-cleans-up-aborted-transactions-2489
  (t/testing "INSERT"
    (xt.sql/submit-tx
      tu/*node*
      [[:sql "INSERT INTO xt_docs (xt$id, xt$valid_from, xt$valid_to)
             VALUES (1, DATE '2010-01-01', DATE '2020-01-01'),
                    (1, DATE '2030-01-01', DATE '2020-01-01')"]])

    (t/is (= [{:committed? false}]
             (xt.d/q tu/*node*
                     '{:find [committed?]
                       :in [tx-id]
                       :where [($ :xt/txs {:xt/id tx-id, :xt/committed? committed?})]}
                     0)))))
```

Attempt was made to call retain-kd-tree on the reference taken out at the start of a transaction, but this caused lots of other failures. See https://github.com/mbutlerw/xtdb/commit/6ecc149c417d2b8eed02947f518310ea9cb12ee9
