### ISSUE TITLE
Clarify writer behaviour for unions - writerForName, writerForType etc

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2590]
Rough spec for Union types:

- Add support for a union map syntax `[:union {'a type-a, 'b type-b}` whereby the keys are arrow field names
- Change rowCopier to only merge/flatten the types of union branches where the names are identical. In the case they are manually defined as above, its the user/developer that defines the desired flattening behaviour. In the case they are named by type (see next bullet point) then it will essentially work as it currently does, which is a merge by type.
- Remove support for `[:union #{type-a type-b}]` syntax. Any existing usages of set syntax can be converted into map syntax via helper fn, which puts each type under a leg of the same name. (Implied restriction here is that set syntax/helper fn does not support multiple elements of the same type, as their names would collide).
- Store writers in `DenseUnionVector`'s writer only by name, having `writerForType` add entries to this map as they are created, using the same "type as name" contract as above.
- Add a writerForName to `DenseUnionVector`s  `IVectorWriter` which returns returns a writer for a given branch name.  Or if provided with a name and col-type definition will create and return a writer for the type and branch name. 
- Replace uses of `writerForTypeId` with `writerbyName`
- Add note not to mix writerForType and writerForName on any given instance of a duv writer. Could be done by convention but could consider adding some kind of check.

**Comment by FiV0** [comment]
We have decided to park this for now as it turned out to be a bit of a rabbit hole. The main issue is that we are trying to use for our reader/writer abstractions for two different use cases:

1. Reading and writing data from the user (dynamic data) that should be represented efficiently in Arrow.
2. Using the reader/writer to write out some fixed schema (maybe the leafs are dynamic).

These two clash in the sense that you don't want your fixed schema to be merged away just because you haven't written to some part of it yet. The following are some points that accumulated while working on this.
 
Our current behaviour for `:union` is a bit special in that certain cases actually don't create a `:union`.
```clj
(col-type->field [:union #{:i64}])
;; => #object[org.apache.arrow.vector.types.pojo.Field 0x3f542513 "union: Int(64, true) not null"]

(col-type->field [:union #{:null :i64}])
;; => #object[org.apache.arrow.vector.types.pojo.Field 0x6216d96 "union: Int(64, true)"]

(col-type->field [:union #{:f64 :i64}])
;; => #object[org.apache.arrow.vector.types.pojo.Field 0x323575bf "union: Union(Dense, null)<f64-0: FloatingPoint(DOUBLE) not null, i64-1: Int(64, true) not null> not null"]
```
So a union is actually only created when two legs are needed. The idea is that our API tries to create an Arrow representation that is kind of efficient on disk. This works out most of the time except if you want to call certain operations that are only supported on unions (`writerForTypeId`).  Is there some general API that would work for these cases without knowing the underlying representation?

The approach of naming things in the `:union` syntax creates problems that we did not run into because it can create all kinds of nested unions we can no longer "merge away". If the name of the leg is important you can not just `[:union {foo :i64}] -> :i64`.
For example a column in the EE was 
```clj
[:union #{:absent [:list [:struct {sku :utf8, qty :i64}]]}]
```
and became
```clj
[:union
          {absent :absent,
           list
           [:list
            [:union
             {struct
              [:struct
               {sku [:union {utf8 :utf8}], qty [:union {i64 :i64}]}]}]]}]
```
It also seems that Arrow does not have something like `vectorForName` for DUVs as leg names don't need to be unique. In that sense our representation (the one proposed in the ticket) would work kind of work against what Arrow favors (type-ids). 

Having two representations for unions (`[:union set]` and `[:union map]`) would not work nicely as it is not clear what `field->col-type` should return.
