### ISSUE TITLE
Why does clojure.lang.Symbol fail the check-eid validation, and why isn't it considered a valid ID?

### ISSUE THREAD

**Issue by ApricotLace** [xtdb/crux#2664]
Why does clojure.lang.Symbol fail the check-eid validation, and why isn't it considered a valid ID?

I've observed that 'id->buffer' is not implemented for clojure.lang.Symbol, as seen here: https://github.com/xtdb/xtdb/blob/29fa08b921e0809f37469cbb40972daa4b88851c/core/src/xtdb/codec.clj#L537-L538
Is there a specific reason for this?

**Comment by jarohen** [comment]
Hey @ApricotLace :wave: 

I'm afraid it's just that it's not a use case that's been requested until now - in our experience, symbols in Clojure tend to be used as syntactic tokens rather than dynamic values to be persisted in a database. Might your use case be better served by strings (for user-provided inputs) or keywords (for a small, closed ID set)? Otherwise, could you provide some example usage?

Cheers,

James
