### ISSUE TITLE
Period structs to have `:xt/from` and `:xt/to` columns

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2701]
Currently, periods returned from period functions are of the form `{:start ..., :end ...}`.

Since we now have `:xt/valid-from`, `:xt/valid-to`, `:xt/system-from`, `:xt/system-to`, these are more consistent.

------

- [x] Rename `start`, `end` to `from`, `to` https://github.com/xtdb/xtdb/pull/2763
- [x] Rename `from`, `to` to `xt/to`, `xt/from` Blocked on https://github.com/xtdb/xtdb/issues/2483

Merged Implementation uses unqualified from, to rather than xt/from, xt/to as we currently only normalise top level column names.

Implementing this change as described in the card would involve exposing xt$from etc. to the user in projected out maps. Therefore unqualified keys seem preferable for now.

**Comment by mbutlerw** [comment]
Merged Implementation uses unqualified `from, to` rather than `xt/from, xt/to` as we currently only normalise top level column names.

Implementing this change as described in the card would involve exposing `xt$from` etc. to the user in projected out maps. Therefore unqualified keys seem preferable for now.

Re-opening card and blocking on #2483

**Comment by jarohen** [comment]
Unblocked after #2483 fix
