### ISSUE TITLE
Adding micrometer metrics to Core engine

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3149]
This ticket includes:
- [x] Adding tx timings and counters to the indexer
  - How fine grained should the metrics be? 
- [x] Adding query timings and counters
- [x] Adding `/promotheus` endpoint for scraping
- [x] Adding a simple Grafana dashboard from the exposed endpoint. This shouldn't be a production ready setup, but rather a dev setup that one can run to improve or work on the metrics reporting.

Open questions:
- Should the `promotheus` scrape endpoint sit together with the http module?
- Should there be some metric of size for a transactions ?

**Comment by jarohen** [comment]
> Should the promotheus scrape endpoint sit together with the http module?

I probably wouldn't, on balance - eventually (once we have authn) we're looking to allow users to expose the HTTP server quite widely, maybe even on the public internet, so it's probably a good idea to keep this separate.

Did you consider working in a push fashion instead? i.e. getting the XT node to push its metrics to the Prometheus server rather than needing to set the Prometheus server to know about the XT nodes? Chances are (in our bench case, at least) the Prometheus server will be relatively long running compared to the bench runs.

> Should there be some metric of size for a transactions ?

Not a bad shout, can add counters for tx-ops, or potentially counters for the amount of events that are put/deleted (i.e. at the live-index level)

Eventually, we'll probably want to extend this to the buffer pool, too - i.e. metrics for cache misses, how long the remote storage reqs are taking, etc.

**Comment by FiV0** [comment]
> Did you consider working in a push fashion instead?

Not really. I agree it's likely not the best model for bench runs, but for monitoring node health it's definitely the model we want to persue, as it's the model that prometheus recommends. https://prometheus.io/docs/practices/pushing/#should-i-be-using-the-pushgateway

> Not a bad shout, can add counters for tx-ops

Yes, that too. I was more thinking of a metric that measures the byte size of the tx or something similiar. Essentially something to differentiate small vs large documents.

**Comment by FiV0** [comment]
A list of potential metrics to add to the core:
- [ ] tx-ops counter.
- [ ] Some indication of the size of the documents ingested.
- [ ] Lag of transaction submitted to transaction indexed (in time and in absolute number of transactions)
