### ISSUE TITLE
SQL JSON API should preserve column ordering

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3237]
Currently, after making a request with an arbitrary SQL query string, there is no simple way to deduce the returned column ordering that is implied within the string.

i.e. `SELECT foo.first_name, foo.last_name FROM foo` might return `[{"foo.last_name": "bar", "foo.first_name": "baz"}]`

Instead, the ordering could be preserved and communicated back to the requester, to provide a more intuitive/natural SQL experience.

This requirement could be satisfied in a variety of ways, e.g.:

1. wrap or prefix the existing array-of-objects response with an object/array that may include columns names, types(!), and other meta information (e.g. execution time, database version, or warnings)
2. return an array-of-tuples instead of array-of-objects, but potentially warranting some variation of 1) also to convey the column names without repeating them inline within every tuple (i.e. `[["foo.first_name", "bar", "foo.last_name", "baz"]])`
3. support multiple return relations and (optionally) have the first return relation be implicit metadata (unusual, but there is [precedent](https://learn.microsoft.com/en-us/sql/connect/jdbc/using-multiple-result-sets?view=sql-server-ver16) in this direction)

Also note that this equally applies to the other SQL query APIs (in-process JVM, etc.) as well, which also return maps, but it's possibly worth thinking through options at the JSON layer first.

**Comment by jarohen** [comment]
cheers @refset - split into #3255 and #3256

**Comment by malcolmsparks** [comment]
I really support 1 (and possibly 3, I think!) rather than 2.
Ergonimcally, JSON objects are really what the JS developer wants to work with, rather than streams of tuples.
The ordering is really metadata, and there should be a way of returning this (and other) metadata for clients that 'know what they're doing'. Perhaps an option on the query to return this info, and perhaps this doesn't have to be set by default.

**Comment by jarohen** [comment]
discussed with @malcolmsparks:

* Yep, agreed, majority JS developers will likely want to work with objects rather than tuples - for this reason, we'll keep `:rows-as` defaulting to `:maps` (#3256).
* The primary reason behind `:rows-as` is for users rendering the results as a table, who expect the column ordering in the table to be the same as their SQL query. (Pgwire is a case of this.)
* We can add further metadata in the future using HTTP response headers should the requirement arise.

**Comment by refset** [comment]
> We can add further metadata in the future using HTTP response headers should the requirement arise.

FYI, seems like even Python's [DB API](https://peps.python.org/pep-0249/) requires knowing the types of the results.

EDIT: prior art https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html
