### ISSUE TITLE
Hyphen in DML nested quoted column reference causes ingestion to stop

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3388]
i.e.

`INSERT INTO docs (xt$id, value) VALUES (1, {"hyphen bug": 1})` works

`INSERT INTO docs (xt$id, value) VALUES (1, {"hyphen-bug": 1})` fails with:

```
Error: java.util.concurrent.ExecutionException

clojure.lang.ExceptionInfo: Ingestion stopped: unknown object type: class xtdb.vector.ValueBox {}
```

https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKHh0JGlkLCB2YWx1ZSkgVkFMVUVTICgxLCB7XCJoeXBoZW4tYnVnXCI6IDF9KSAifV0%3D&query=U0VMRUNUICogRlJPTSBkb2Nz

**Comment by jarohen** [comment]
@refset: sorry mate, had a quick look at this one and it's not straightforward :slightly_frowning_face: 

cause is that in StructVectorWriter we're not clear about whether we should be preserving the casing of the caller. generally speaking, we should, because that's what we do throughout the expression engine - it's up to the query language compiler to normalise if required - but things like put-docs don't because it would involve a very expensive Object->Object transformation which was previously lighting up our profiler.

Think it's best we down-prio this one for the time being on account of its probability - I doubt many SQL users will be including hyphens in delimited identifiers in this way? and, if they do, this kind of issue should very quickly show up in their dev environments?

**Comment by jarohen** [comment]
I've added the test case - see the linked commit ^^

**Comment by refset** [comment]
Not sure what changed, but looks fixed now.
