### ISSUE TITLE
Disallow temporal period specifications on CTE

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3440]
Remove from grammar or add support (please).

[Play link](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsICdiYXInKSJ9LHsidHhzIjoiSU5TRVJUIElOVE8gZG9jcyAoX2lkLCBmb28pIFZBTFVFUyAoMSwgJ2ZvbycpIiwic3lzdGVtLXRpbWUiOm51bGx9XQ%3D%3D&query=V0lUSCBkYXRhIEFTICgKICBTRUxFQ1QgKgogIEZST00gZG9jcwopClNFTEVDVCAqCkZST00gZGF0YSBGT1IgQUxMIFZBTElEX1RJTUU%3D):
```sql
-- at day 1
INSERT INTO docs (_id, foo) VALUES (1, 'bar')
-- at day 2
INSERT INTO docs (_id, foo) VALUES (1, 'foo')

WITH data AS (
  SELECT *
  FROM docs
)
SELECT *
FROM data FOR ALL VALID_TIME
```

**Comment by Akeboshiwind** [comment]
This query:
```sql
SELECT docs1.*
FROM generate_series(DATE '2024-06-01', DATE '2024-06-02') AS d(d)
JOIN docs1 FOR ALL VALID_TIME
  ON docs1.VALID_TIME CONTAINS d.d
JOIN docs2 FOR ALL VALID_TIME
  ON docs1.otherId = docs2._id
     AND docs2.VALID_TIME CONTAINS d.d
```

Could become:
```sql
WITH data AS (
  SELECT docs1.*
  FROM docs1
  JOIN docs2 ON docs1.otherId = docs2._id
)
SELECT *
FROM data FOR ALL VALID_TIME
JOIN generate_series(DATE '2024-06-01', DATE '2024-06-02') AS d(d)
  ON data.VALID_TIME CONTAINS d.d
```

**Comment by refset** [comment]
After reviewing some options here with @mbutlerw it seems like the idea of adding a temporal period specification to CTEs is not straightforward because of the as-of-now default semantics combined with the lack of explicit column projections.

Ideally, in the simplest case, it would be possible to run a singularly defined existing as-of-now query multiple times, as a parameterised subquery, against multiple as of timestamps in one go (as a nested loop in a single query, without the roundtrip overheads of executing as multiple statements). However there is a potentially irreconcilable tension in the desire to re-use an as-of-now query ~unchanged whilst achieving that.

Suggestions for future exploration include: extending query parameters to incorporate additional temporal functionality (i.e. much more than just the as-of-now boolean, such a start-stop-step range of timestamps), or create some kind of new syntax that could alter the scope of temporal periods.

For now though it would be best to disallow this invalid grammar explicitly.

**Comment by jarohen** [comment]
> the idea of adding a temporal period specification to CTEs is not straightforward because of the as-of-now default semantics combined with the lack of explicit column projections.

It's more that the CTE is an arbitrary SQL query that returns a relation, and intermediate relations don't have any notion of system versioning - the as-of-now default semantics shouldn't affect it. CTEs do have known column projections, too - just that none of the columns (even if they happen to be named `_system_from` etc) have the attached meaning of being a 'system versioning column' in the same way that columns on a base table would.

> For now though it would be best to disallow this invalid grammar explicitly.

Pedantic, but we can't disallow this at the grammar level - it's syntactically valid - but we should throw an analyzer error.

**Comment by refset** [comment]
> intermediate relations don't have any notion of system versioning

For clarity, the original thought was that it should push down any period specs to all base tables within the CTE (but only further _constraining_ any existing period specs within the CTE, and not widening them!) - agreed that non-base relations, including CTEs, don't/shouldn't/can't have meaningful versioning.
