### ISSUE TITLE
Auctionmark up and running on Azure

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3477]
Potential milestones:

1. a single node runs the load-phase and a ~10min run. Main aim is to get the container up and running:
   * using local disk tx-log and storage, 
   * able to see the logs
   * created using an [ARM](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/overview) template (or equivalent, but preferably using their IaC tool)
2. Metrics posted to the Azure metrics service (i.e. their CloudWatch equivalent)
3. Three nodes running in a cluster, sharing the tx-log and object-store.
   * The object-store additionally requires a small notification system (on AWS we use SQS and SNS) to inform nodes when files have been uploaded to the object store. This prevents us needing to continuously make list-objects calls on the object store, which tends to be expensive, slow, and requires pagination.

TODOS:
- [x] Getting a single node running with local log & storage.
- [x] Terraform scripts with all of the necessary infra & roles setup. 
- [x] Getting a single node running with:
  - [x] blob storage.
  - [x] event hub log
- [x] Fix issues with multipart ASAP.
- [x] Investigate weird behaviour from the file watcher
- [x] Get running with eventhub and figure out what that might need/issues there.
- [x] Persistent mounted storage on container app - for local disk cache, etc.
- [x] Pull out general fixes off of the branch such that we can get them merged to main ASAP, then aim for an initial merge of single node azure testing.

## Updates (Dan M & Tim)

Some updates on current state of this:
- We've found that to get app client credentials working with managed identities we needed to add additional config - we have something working there, you need to pass in relevant config to the client with the user managed identity id. Have added this to our various Azure configuration classes, will likely document up later/pull out to main as appropriate.
- Added some custom retry behaviour into the blob storage object store too - not sure if it has some by default but experimenting with that.
- Doesn't seem to get very far on the auctionmark bench/writing to blob storage, might be something to do with passing through arrow files:
  - Main error being returned was InvalidBlobOrBlock
  - Seems to be related to multiparts and how we use them within upload-arrow-file - turning off multipart seems to fix things somewhat
    - Gets us through the load stage and onto the main loop.
    - Though obviously might have some impact on performance - some kind of bug in that implementation, anyway.
 - In the azure tests we test out our uploading of arrow files using the `tpch test` at scale factor 0.05. This does actually upload arrow files that are large enough to trigger multipart uploads, but doesn't hit the same `InvalidBlobOrBlock` problems. Perhaps a result of size in auctionmark, though I would expect the error to get thrown later in that case.

## Update 2

We've had a successful ten minute run with just storage blobs being used, though observed a few interesting properties/bugs in the mean time:
- The service bus config that we have on main - ie, that we use in the nightly tests - was failing. This was because we actually hit the 1GB size limit of the service bus - because messages were being infinitely retained on said service bus. Think that we should update any docs & templates to ensure that this has a fixed time to live on the messages (1 day, perhaps?)
  - If you span up a new node it would first call to list from the object store rather than looking at past messages from the service bus (indeed, it starts reading from the most recent point rather than oldest), so perhaps time to live here could be very short.
- We noticed that there was another problem with multipart uploads - namely that the file watcher wouldnt properly pick them up. This would mean, in practise, in a clustered node, we would be missing files. Essentially sends a different API message to PutBlob on the ServiceBus (PutBlockList), which we were not listening for.

Going to card the above two up and push fixes for them individually to main.

**Comment by danmason** [comment]
Update:
- Can replicate this by upscaling TPCH, but can replicate far quicker by simply running azure against auctionmark locally.
- Observations: we do seem to hit the multipart path fairly quickly and we observe that the errors start getting thrown as soon as we hit `10` current blocks within the multipart upload. That's interesting to say the least, considering the azure stated limit of uncommitted blocks is 100000 (https://learn.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs) 
- Was wondering if it _might_ be related to the block id we generate, rather than the actual number of blocks in the upload - testing against this (ie, by going FROM block number 10 rather than block number 1), we actually didn't throw an error. This is strange, to say the least, but definitely suggests it's related to the block id itself.
  - Essentially we encode the bytes of the block number in base 64. 
  - When block number 1 - block id when printed looks like `MQ==`
  - When block number 10 - block id when printed looks like `MTA=`
  - Essentially - seems related to the length of the block number/id (ie, would expect the same to happen if you went from block number 99 to block number 100)
- Don't really need to encode the block number at all, so just going to use UUIDs

**Comment by danmason** [comment]
Merged an initial cut of this, a single node running with:
- Azure blob based remote storage
- Eventhub based txLog

In terms of following up:
- Setting up / testing a clustered run to be done as a piece of follow up work, in #3530 
- Noted some performance issues against eventHub (slow load phase) - going to investigate those, starting with a known piece of work we needed to do against it, #3400
