### ISSUE TITLE
SQL query repeatability with `SETTING BASIS TO <timestamp>` prefix

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3505]
Currently (since https://github.com/xtdb/xtdb/pull/3448) you can do e.g. `SETTING DEFAULT SYSTEM_TIME TO AS OF TIMESTAMP '2024-07-15T12:37:00' SELECT * FROM PEOPLE;` but this is insufficient for true repeatability because the query body can easily override the SYSTEM_TIME scoping (and thereby see changes that happened _after_ the timestamp).

The proposal is `SETTING BASIS TO <timestamp>`

Possibly related / superseding: https://github.com/xtdb/xtdb/issues/2205

**Comment by jarohen** [comment]
One thing to consider is that basis affects which transaction the client should await - i.e. if it is set to a value after the latest-submitted-tx of that client, then the client needs to await the given transaction before analysing the SQL (because the schema might have changed in the interim).

One option is that this could be a session variable (i.e. `SET BASIS TO|= <timestamp>` rather than `SETTING` at the start of the query). This would then take effect either for the current/next transaction or session, depending on the transaction state.

**Comment by jarohen** [comment]
Ignore me, parsing in two phases was simple enough 🙂
