### ISSUE TITLE
Request: str, keyword functions in standard library

### ISSUE THREAD

**Issue by esp1** [xtdb/crux#3794]
I'd like to suggest adding a `str` function to the standard library to stringify any type. This would allow the existing standard library string functions to be used to query non-string types - e.g. query for keywords or uuids by substring or prefix.

I'd also like to suggest adding `name` and `namespace` functions in the standard library for retrieving the name and namespace of a keyword.

**Comment by refset** [comment]
Thanks for opening the issue @esp1 - you can use `CAST(foo AS text)` in many cases, does it work for your needs?

For complex types you will get a cast error currently though, e.g. [Play](https://play.xtdb.com/?version=2.0.0-b1&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsIHtiYXo6IFtEQVRFICcyMDIwLTAxLTAxJywgMy4xNF19KSJ9XQ%3D%3D&query=U0VMRUNUIENBU1QoZm9vIEFTIHRleHQpLCBmb28gRlJPTSBkb2Nz)

**Comment by refset** [comment]
Workaround example for `name`: `SUBSTRING('user/id' FROM POSITION('/' IN 'user/id') + 1)`  [Play](https://play.xtdb.com/?version=2.0.0-b1&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsICdiYXInKSJ9XQ%3D%3D&query=U0VMRUNUIFNVQlNUUklORygndXNlci9pZCcgRlJPTSBQT1NJVElPTignLycgSU4gJ3VzZXIvaWQnKSArIDEpLCBmb28gRlJPTSBkb2Nz)

**Comment by refset** [comment]
Workaround example for `namespace`:`SUBSTRING('user.abc/id' FROM 1 FOR POSITION('/' IN 'user.abc/id') - 1)` [Play](https://play.xtdb.com/?version=2.0.0-b1&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsICdiYXInKSJ9XQ%3D%3D&query=U0VMRUNUIFNVQlNUUklORygndXNlci5hYmMvaWQnIEZST00gMSBGT1IgUE9TSVRJT04oJy8nIElOICd1c2VyLmFiYy9pZCcpIC0gMSkgQVMgbmFtZXNwYWNlX3BhcnQ7)

**Comment by esp1** [comment]
I think CAST is only available in SQL, and even when I try it it fails if I have stored values as keywords in the database:
```
SELECT CAST(type$id as text) from TYPES;

Query 1 ERROR at Line 1: : ERROR:  Unsupported cast: ':keyword' -> ':utf8'
```
Also, I have been trying to use XTQL, and I didn't see documentation for how to cast types there.

The SUBSTRING examples could work if I store keywords as strings in xtdb, but I don't think they will work if I have stored values as keywords.

**Comment by refset** [comment]
The `cast` function is definitely already available in XTQL but I can't see that we have a way of referring to the target types using literals/strings yet, e.g. [Play](https://play.xtdb.com/?version=2.0.0-b1&type=xtql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6Ils6cHV0LWRvY3MgOmRvY3Mgezp4dC9pZCAxIDpmb28gXCJiYXJcIn1dIn1d&query=KC0%2BIChmcm9tIDpkb2NzIFt4dC9pZCBmb29dKQogICh3aXRoIHs6YmFyIChjYXN0IHh0L2lkIDp0ZXh0KX0pKQ%3D%3D)

The real issue here though is that we simply haven't built out the standard library at all yet for working with the `keyword` type, beyond basic round-tripping. Happy to discuss priorities any time but I can't promise we'll get to this soon without understanding more about what you're trying to achieve - feel free to message: hello@xtdb.com

In the meantime I would recommend treating keyword storage (assuming you want to reference the keywords in queries) in the same way you would handle it when using regular SQL/Postgres (e.g. just using strings with extra transformations).

**Comment by esp1** [comment]
No worries, I can work around it as you say. I'm evaluating xtdb right now and feeling out where the edges are, and this was one hole I fell into along the way. I would maybe just suggest a callout in documentation somewhere about the limitations of working with keywords/uuids in the database for the time being until those features are more well supported, so others can avoid falling into the same hole.

**Comment by jarohen** [comment]
Hey @esp1 - should now have access to `local-name`, `namespace`, `keyword` and `str` in XTQL :slightly_smiling_face: 

I've pushed the `edge` Docker label, so it'll be in `ghcr.io/xtdb/xtdb:edge`, or if you've got the XTDB repo cloned, it'll be available in a REPL on the `main` branch.

~Will also add~ Have also added support for these to SQL.

HTH!

**Comment by esp1** [comment]
Amazing - thank you!

**Comment by esp1** [comment]
@jarohen is there a new version of `com.xtdb/xtdb-api` I need to use this? I updated myserver to use `ghcr.io/xtdb/xtdb:edge`, but my client is using `com.xtdb/xtdb-api {:mvn/version "2.0.0-beta3"}`, and the new XTQL functions don't seem to be available there.

**Comment by jarohen** [comment]
Hey @esp1 - it's not yet available in a released version, but if you use `nightly` or `edge` they should be available. Maybe Docker's caching the `edge` image, try `--pull=always`?
