### ISSUE TITLE
Implicit column alias for UNNEST

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3848]
e.g. in Postgres this works:

```sql
SELECT foo
FROM UNNEST(ARRAY[1, 2, 2, 5, NULL]) AS foo
```

But in XT currently we have to be explicit about the table and column alias, otherwise you get empty rows back:

```sql
SELECT bar
FROM UNNEST(ARRAY[1, 2, 2, 5, NULL]) AS foo (bar)
```

We've explicitly elected to *differ* from Postgres here - see [below comment](https://github.com/xtdb/xtdb/issues/3848#issuecomment-2465635093).

----
(original report)

```sql
INSERT INTO people
RECORDS {_id: 6,
         name: 'fred',
         info: {contact: [{loc: 'home',
                           tel: '123'},
                          {loc: 'work',
                           tel: '456',
                           registered: DATE '2024-01-01'}]}}
```

When we try to unnest info.contact in XT, we currently get the following:

```sql
SELECT cs.* FROM people, UNNEST((info).contact) cs;

                      _column_1
------------------------------------------------------
 {"loc":"home","tel":"123"}
 {"loc":"work","registered":"2024-01-01","tel":"456"}
(2 rows)
```

i.e. the return column is `_column_1`.

Trying to (e.g.) filter on this column (without knowing XT calls it `_column_1`) might lead to the following query:

```sql
SELECT con
FROM people, UNNEST((info).contact) as con
WHERE (con).loc = 'work'
```

which yields the warning that the `con` column doesn't exist.

**Comment by jarohen** [comment]
Quoth the SQL spec (§7.6, Syntax Rule 7.m.ii.1):

> (A) If any ET_j_, 1 (one) ≤ j ≤ NCV, is a row type, then [...] let FN_j,i_, 1 ≤ i ≤ DET(j), be the name of the i-th field in ET_j_.
(B) For each ET_j_ that is not a row type, let DET(j) be 1 (one) and let FN_j,1_ be an <identifier> that is not equivalent to any other <identifier> contained in TP.

In SQL, in `UNNEST(...) AS a (b, c)`, `a` is considered a table ('correlation') name, `b`/`c` are column names - as such, Postgres is using the table alias as a column name.

The [Postgres documentation](https://www.postgresql.org/docs/17/queries-table-expressions.html#QUERIES-TABLEFUNCTIONS) on the subject is not immediately clear that this is intentional:

> Table functions are functions that produce a set of rows, made up of either base data types (scalar types) or composite data types (table rows). 
>
> [...]
>
> The special table function `UNNEST` [... i.e. UNNEST is considered a table-fn]
>
> [...]
>
> If no table_alias is specified, the function name is used as the table name.
>
> If column aliases are not supplied, then for a function returning a base data type, the column name is also the same as the function name. For a function returning a composite type, the result columns get the names of the individual attributes of the type.

I read that that the column name should be `unnest` if only the table alias is provided?

In the original report, we did briefly consider using the column name on the inside of the unnest as the default column name on the outside - however, the inner column name is likely to be a plural, which isn't the name we'd necessarily want for the singular element on the outside. 

Hence, let's get the user to be explicit about what they want to name the element.
